// console.log('Hello world')
// veriable 
// let num = 1327584596500;

// console.log(num); 


 
// let y = 10 
// const z = 20; 
// y = 20; 
//  console.log(y); 
//  z = 30; 
//  console.log(z);


// let num = "john"//string
// let age = 25 //number
// let isActive = ture //bolean
// let x //undefined 
// let y = null //null-> Empty value 

// console.log(name,age, isActive,x,y);

// //Non primitive
// let colurs =  ["red", "orange","blue"]

 
       